---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver_config:
      network:
        - ["private_network", {ip: "192.168.33.15"}]

suites:
  - name: default
    run_list:
      - recipe[app::jenkins]
    attributes:
